// <auto-generated />
using System;
using GADApplication.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GADApplication.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241003212230_AddedVerificationFileTable")]
    partial class AddedVerificationFileTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GADApplication.Models.Activity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActivityType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Budget")
                        .HasColumnType("real");

                    b.Property<string>("Cause")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("GPBId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Objective")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PerformanceIndicators")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SourceBudget")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("GPBId");

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("GADApplication.Models.GAR", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActivityId")
                        .HasColumnType("int");

                    b.Property<string>("ActualResult")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GPBId")
                        .HasColumnType("int");

                    b.Property<int>("TotalBudgetUsed")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId")
                        .IsUnique();

                    b.HasIndex("GPBId");

                    b.ToTable("GARs");
                });

            modelBuilder.Entity("GADApplication.Models.GARActivity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActivityId")
                        .HasColumnType("int");

                    b.Property<string>("ActualResult")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GARId")
                        .HasColumnType("int");

                    b.Property<double>("TotalBudgetUsed")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId");

                    b.HasIndex("GARId");

                    b.ToTable("GARActivities");
                });

            modelBuilder.Entity("GADApplication.Models.GPB", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MFOPAPOrPPA")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResponsibleUnit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("TotalGAAOrBudget")
                        .HasColumnType("float");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("GPBs");
                });

            modelBuilder.Entity("GADApplication.Models.Mandate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ActivityId")
                        .HasColumnType("int");

                    b.Property<string>("ChedMemo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RepublicAct")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId");

                    b.ToTable("Mandates");
                });

            modelBuilder.Entity("GADApplication.Models.VerificationFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GARActivityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UploadDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("GARActivityId");

                    b.ToTable("VerificationFile");
                });

            modelBuilder.Entity("GADApplication.Pages.GPBPage.ActivityViewModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActivityType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Budget")
                        .HasColumnType("real");

                    b.Property<string>("Cause")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GPBViewModelId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Objective")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PerformanceIndicators")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SourceBudget")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GPBViewModelId");

                    b.ToTable("ActivityViewModel");
                });

            modelBuilder.Entity("GADApplication.Pages.GPBPage.GPBViewModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MFOPAPOrPPA")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResponsibleUnit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("TotalGAAOrBudget")
                        .HasColumnType("float");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("GPBViewModel");
                });

            modelBuilder.Entity("GADApplication.Pages.GPBPage.MandateViewModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ActivityViewModelId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ActivityViewModelId");

                    b.ToTable("MandateViewModel");
                });

            modelBuilder.Entity("GADApplication.Models.Activity", b =>
                {
                    b.HasOne("GADApplication.Models.GPB", "GPB")
                        .WithMany("Activities")
                        .HasForeignKey("GPBId");

                    b.Navigation("GPB");
                });

            modelBuilder.Entity("GADApplication.Models.GAR", b =>
                {
                    b.HasOne("GADApplication.Models.Activity", "Activity")
                        .WithOne("GAR")
                        .HasForeignKey("GADApplication.Models.GAR", "ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GADApplication.Models.GPB", "GPB")
                        .WithMany("GARs")
                        .HasForeignKey("GPBId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activity");

                    b.Navigation("GPB");
                });

            modelBuilder.Entity("GADApplication.Models.GARActivity", b =>
                {
                    b.HasOne("GADApplication.Models.Activity", "Activity")
                        .WithMany()
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GADApplication.Models.GAR", "GAR")
                        .WithMany("Activities")
                        .HasForeignKey("GARId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activity");

                    b.Navigation("GAR");
                });

            modelBuilder.Entity("GADApplication.Models.Mandate", b =>
                {
                    b.HasOne("GADApplication.Models.Activity", "Activity")
                        .WithMany("Mandates")
                        .HasForeignKey("ActivityId");

                    b.Navigation("Activity");
                });

            modelBuilder.Entity("GADApplication.Models.VerificationFile", b =>
                {
                    b.HasOne("GADApplication.Models.GARActivity", null)
                        .WithMany("VerificationFiles")
                        .HasForeignKey("GARActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GADApplication.Pages.GPBPage.ActivityViewModel", b =>
                {
                    b.HasOne("GADApplication.Pages.GPBPage.GPBViewModel", null)
                        .WithMany("Activities")
                        .HasForeignKey("GPBViewModelId");
                });

            modelBuilder.Entity("GADApplication.Pages.GPBPage.MandateViewModel", b =>
                {
                    b.HasOne("GADApplication.Pages.GPBPage.ActivityViewModel", null)
                        .WithMany("Mandates")
                        .HasForeignKey("ActivityViewModelId");
                });

            modelBuilder.Entity("GADApplication.Models.Activity", b =>
                {
                    b.Navigation("GAR")
                        .IsRequired();

                    b.Navigation("Mandates");
                });

            modelBuilder.Entity("GADApplication.Models.GAR", b =>
                {
                    b.Navigation("Activities");
                });

            modelBuilder.Entity("GADApplication.Models.GARActivity", b =>
                {
                    b.Navigation("VerificationFiles");
                });

            modelBuilder.Entity("GADApplication.Models.GPB", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("GARs");
                });

            modelBuilder.Entity("GADApplication.Pages.GPBPage.ActivityViewModel", b =>
                {
                    b.Navigation("Mandates");
                });

            modelBuilder.Entity("GADApplication.Pages.GPBPage.GPBViewModel", b =>
                {
                    b.Navigation("Activities");
                });
#pragma warning restore 612, 618
        }
    }
}
